package utils

import (
	"bytes"
	"errors"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
	"time"
)

func Test_ResponseJson(t *testing.T) {
	responseJsonTests := []struct {
		testName string
		code int
		message string
		expectedJsonResponse string
	} {
		{"Successful Login", http.StatusOK, "Successfully Logged In!", `{"code":200,"message":"Successfully Logged In!"}`},
		{"Duplicate username", http.StatusBadRequest, "Username already exists. Please try again.", `{"code":400,"message":"Username already exists. Please try again."}`},
	}

	for _, e := range responseJsonTests {
		// Creating a mock ResponseWriter
		w := httptest.NewRecorder()

		ResponseJson(w, e.code, e.message)

		// Read the response body as a string
		body, _ := io.ReadAll(w.Result().Body)
		actual := string(body)

		expected := e.expectedJsonResponse
		if actual != expected {
			t.Errorf("%s: expected %s but got %s", e.testName, e.expectedJsonResponse, actual)
		}
	}
}

func Test_InternalServerError(t *testing.T) {
	// Create a new bytes.Buffer to capture the log output
	var buf bytes.Buffer

	// Redirect log output to a different destination set as a buffer
	// By default, log message are written to the standard error stream os.Stderr
	log.SetOutput(&buf)

	/* Reset the log output destination back to os.Stderr
	 * In the test function, we redirect the log output to a buffer so that we can capture
	 * and test the log messages generated by the function being tested. However, we need to make
	 * sure that we reset the log output destination back to `os.Stderr` so that subsequent log
	 * messages in the test suite are written to the standard error stream instead of to the buffer. */
	defer func() {
		log.SetOutput(os.Stderr)
	} ()

	// Generate an error
	err := errors.New("test error")

	w := httptest.NewRecorder()

	// Calling the function
	InternalServerError(w, "Internal Server Error (testing):", err)
	actualOutput := buf.String()

	// Get date time to compare with logs
	dt := time.Now()
	dtString := dt.Format("2006/01/02 15:04:05")
	expectedOutput := dtString + " Internal Server Error (testing): test error\n"
	
	if actualOutput != expectedOutput {
		t.Errorf("Incorrect Internal Server Error: expected %q but got %q", expectedOutput, actualOutput)
	}
}